### ISSUE TITLE
"unknown" value in tmsu tags column

### ISSUE THREAD

**Issue by aerojustaero** [talklittle/tmsu-nautilus-rs#19]
And at same times all other places tab properties & menu show real tags.
I have tags name=value 
When scroll files it is possible to see tag on some time on columns and then it disappears.

**Comment by aerojustaero** [comment]
after editing tags value shows on some time and then disappears.

**Comment by talklittle** [comment]
What Nautilus version?

What other Nautilus extensions do you have installed?

Nautilus extensions have a bug where the ordering sometimes matters, based on the filename of the extensions. E.g. `libtmsu-nautilus.so` behaves differently than `libnautilus-tmsu.so` because it affects the order of extension loading. I've seen the "unknown" value in the column in this kind of situation.

You can try renaming the `.so` file and then restarting nautilus (`nautilus -q`) and see if a different filename works around the problem.

**Comment by aerojustaero** [comment]
just tried to rename lib1tmsu-nautilus.so with no effect

nautilus 3.14.3

/usr/lib/nautilus/extensions-3.0/libdeja-dup.so
/usr/lib/nautilus/extensions-3.0/libevince-properties-page.so
/usr/lib/nautilus/extensions-3.0/libnautilus-fileroller.so
/usr/lib/nautilus/extensions-3.0/libnautilus-sendto.so
/usr/lib/nautilus/extensions-3.0/libnautilus-share.so
/usr/lib/nautilus/extensions-3.0/libnautilus-share-extension.so
/usr/lib/nautilus/extensions-3.0/libterminal-nautilus.so
/usr/lib/nautilus/extensions-3.0/libtmsu-nautilus.so
/usr/lib/nautilus/extensions-3.0/libtotem-properties-page.so

**Comment by chrismvasq** [comment]
Same issue. When I look at the file under properties the tags are present. But just not showing in the column. Tried changing the name as well to no effect. Adding/editing a tag has no effect. 

Nautilus 3.14.3

/usr/lib/nautilus/extensions-3.0/libdeja-dup.so
/usr/lib/nautilus/extensions-3.0/libnautilus-dropbox.so
/usr/lib/nautilus/extensions-3.0/libnautilus-fileroller.so
/usr/lib/nautilus/extensions-3.0/libnautilus-sendto.so
/usr/lib/nautilus/extensions-3.0/libnautilus-share-extension.so
/usr/lib/nautilus/extensions-3.0/libnautilus-share.so
/usr/lib/nautilus/extensions-3.0/libnautilus-tmsu.so
/usr/lib/nautilus/extensions-3.0/libterminal-nautilus.so
/usr/lib/nautilus/extensions-3.0/libtotem-properties-page.so

**Comment by talklittle** [comment]
I am able to reproduce this bug on tmsu-nautilus 0.5.5 and 0.6.1, on Ubuntu Files 3.36.3. If I use either the Edit dialog or the Properties edit dialog to make two edits in a row, then the column becomes "unknown". On the other hand, one single edit is properly communicated back to the columns provider.

**Comment by talklittle** [comment]
One problem source appears to be `nautilus_file_info_invalidate_extension_info()` called too many times too quickly, with a possible race condition putting the file metadata into a bad state.

The tags edit dialog had a bug calling this function too many times, now fixed in tmsu-nautilus extension v0.6.2.

However, the "unknown" column issues when simply scrolling are not reproducible, notably when no other extensions are installed alongside tmsu-nautilus. I saw the problem in some situations years ago, on a system with other extensions installed. My guess is there were too many Nautilus extensions all updating file metadata at the same time, causing a similar race condition and confusing Nautilus.

Closing this issue for now due to lack of reproducibility.
